# Docker Compose per DigitalOcean App Platform
# Solo servizio app - DB managed da DigitalOcean
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.digitalocean
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env.production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped