# DigitalOcean App Platform Configuration
# Sistema Prenotazioni Centro Medico - Biofertility
name: centro-biofertility-prenotazioni
region: fra
services:
- name: web
  source_dir: /
  github:
    repo: Gabriele8967/Prenotazioni-Centro-Medico--Biofertility
    branch: main
    deploy_on_push: true
  run_command: npm start
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  env:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "3000"
  - key: FRONTEND_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: MYSQL_HOST
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: MYSQL_PORT
    value: "25060"
  - key: MYSQL_DATABASE
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: MYSQL_USER
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: MYSQL_PASSWORD
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: EMAIL_USER
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: EMAIL_PASSWORD
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: COMPANY_EMAIL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: GOOGLE_CLIENT_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: GOOGLE_CLIENT_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: GOOGLE_REFRESH_TOKEN
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: GOOGLE_CALENDAR_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: JWT_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: WEBHOOK_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET

databases:
- name: biofertility-db
  engine: MYSQL
  version: "8"
  size: db-s-dev-database
  num_nodes: 1

static_sites:
- name: frontend
  source_dir: /react-frontend
  github:
    repo: Gabriele8967/Prenotazioni-Centro-Medico--Biofertility
    branch: main
    deploy_on_push: true
  build_command: npm run build
  output_dir: /dist
  environment_slug: node-js
  env:
  - key: VITE_API_URL
    scope: BUILD_TIME
    type: SECRET
  - key: VITE_FRONTEND_URL
    scope: BUILD_TIME
    type: SECRET